model:
  backbone: "resnet18"
  cnn_model: "efficientnet_b0"
  num_classes: 100
  pretrained: false

train:
  batch_size: 64
  epochs: 50
  device: "cuda"
  save_every: 10

optimizer:
  type: "AdamW"
  lr: 0.001
  weight_decay: 0.0001

data:
  root: "./data"
  num_workers: 4
  augmentations:
    - "RandomCrop"
    - "RandomHorizontalFlip"
    - "ColorJitter"
    # - "RandomRotation"

logging:
  log_dir: "./logs"
  log_interval: 100
