model:
  backbone: "resnet18"
  cnn_model: "efficientnet_b0"
  num_classes: 100
  pretrained: false
  dropout_rate: 0.3  # Dropout 추가

train:
  batch_size: 64
  epochs: 200
  device: "cuda"
  save_every: 10
  early_stopping: true  # Early Stopping 추가

optimizer:
  type: "AdamW"
  lr: 0.0005  # 학습률 감소
  weight_decay: 0.001  # Weight Decay 증가

data:
  root: "./data"
  num_workers: 8
  augmentations:
    - "RandomCrop"
    - "RandomHorizontalFlip"
    - "ColorJitter"
    - "RandomRotation"
    - "CutMix"
    - "MixUp"  # 추가적인 데이터 증강

logging:
  log_dir: "./logs"
  log_interval: 100

scheduler:
  type: "CosineAnnealingLR"
  T_max: 200
  eta_min: 1e-6
